name: portfolio-dev

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: portfolio-postgres-dev
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - portfolio-postgres-data:/var/lib/postgresql/data

volumes:
  portfolio-postgres-data:
